config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
get 'journeys' => 'journeys#index'
get 'journey/:id' => 'journeys#show', as: 'journey'
get 'courses' => 'courses#index'
# get 'events' => 'events#index'
# get 'events/new' => 'events#new'
# get 'events/:id' => 'events#show', as: 'event'
# get 'events/:id/edit' => 'events#edit', as: 'edit_event'
# patch 'events/:id' => 'events#update'
resources :events
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
end

app/models/event.rb
# frozen_string_literal: true

# Business Logic
class Event < ApplicationRecord
  validates :name, :location, presence: true

  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :image_file, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: 'must be a JPG or PNG image'
  }

  def self.upcoming
    where('starts_at > ?', Time.now).order('starts_at')
  end

  def free?
    price.blank? || price.zero?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# CRUD Event
class EventsController < ApplicationController
  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = event_notice
      redirect_to @event
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url, status: :see_other
  end

  private

  def event_params
    params.require(:event)
          .permit(:name, :description, :location, :price, :starts_at, :image_file)
  end

  def event_notice
    'Evento atualizado com sucesso!' # 'Event successfully updated!'
  end
end

app/controllers/journeys_controller.rb
# frozen_string_literal: true

# CRUD Jorney
class JourneysController < ApplicationController
    def index
        @journeys = ['Converse com o seu eu do passado', 'RISC', 'Mapa da Vida']
    end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# UsersController manages CRUD actions for the User model
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy!

    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

# Helper
module EventsHelper
    def price(event)
      if event.free?
        'Free'
      else
        number_to_currency(event.price, precision: 0)
      end
    end

    def day_and_time(event)
      event.starts_at.strftime('%B %d at %I:%M %P')
    end
end

app/helpers/journeys_helper.rb
# frozen_string_literal: true

module JourneysHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/courses/index.html.erb
<ul>
  <%@courses.each do |course|%>
    <li><%= course.name%></li>
  <%end%>
</ul>

app/views/events/_form.html.erb
<%= form_with(model: event) do |f| %>
  <%= render "shared/errors", object: event %>
  <%= f.label :name, "Nome" %>
  <%= f.text_field :name %>
  <%= f.label :description, "Resumo" %>
  <%= f.text_area :description, rows: 5 %>
  <%= f.label :location, "Local"%>
  <%= f.text_field :location %>
  <%= f.label :price, "Preço" %>
  <%= f.number_field :price %>
  <%= f.label :starts_at, "Data" %>
  <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>
  <%= f.label :image_file %>
  <%= f.text_field :image_file %>
  <%= f.submit "Criar Evento" %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>
<%= render "form", event: @event %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <section class="event">
    <div class="image">
      <%= image_tag event.image_file %>
    </div>
    <div class="summary">
      <h2><%= link_to event.name, event %></h2>
      <h3><%= day_and_time(event) %> in <%= event.location %></h3>
      <span class="price">
        <%= price(event) %>
      </span>
      <p>
        <%= truncate(event.description, length: 35, separator: ' ') %>
      </p>
    </div>
  </section>
<% end %>
<section class="admin">
  <%= link_to "Add New Event", new_event_path, class: "button" %>
</section>

app/views/events/new.html.erb
<h1>Criar Evento</h1>
<%= render "form", event: @event %>

app/views/events/show.html.erb
<section>
  <div>
    <h1><%= @event.name %></h1>
    <p>
      <%= @event.description %>
    </p>
  </div>
</section>
<section class="admin">
  <%= link_to "Edit", edit_event_path(@event), class: "button" %>
  <%= link_to "Delete", @event, class: "button",
        data: { turbo_method: :delete, turbo_confirm: "Você tem certeza que quer excluir?" } %>
</section>

app/views/journeys/index.html.erb
<ul>
  <%@journeys.each do |journey|%>
    <li><%=link_to(journey, journey_path(journey))%></li>
    <%=  %>
  <%end%>
</ul>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    © <%= Time.now.year %> gotech.education | Aprenda Business, Tecnologia e SoftSkills | Todos os direitos reservados.
    <br>
    Desenvolvido por <a href="https://gotech.education" class="footer-link">gotech.education</a>
  </p>
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>GotechRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "turbo", type: "module" %>
</head>

app/views/layouts/_header.html.erb
<head>
  <title>GotechRails</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "turbo", type: "module" %>
</head>

app/views/layouts/_navbar.html.erb
<header>
  <%= image_tag("favicon.jpeg", width: "100", height: "100") %>
  <%= link_to("Eventos", events_path, class: "white-bg") %>
  <%= link_to("Jornadas", journeys_path, class: "white-bg") %>
  <%= link_to("Cursos", courses_path, class: "white-bg") %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render "layouts/head"%>
  <body>
    <%= render "layouts/navbar"%>
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <%= render "shared/errors", object: user %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.label :password_confirmation, style: "display: block" %>
    <%= form.password_field :password_confirmation %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<h1><%=pluralize(@users.size, "User") %></h1>
<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>
<%= link_to "New user", new_user_path %>
<hr>
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>
<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>